auto: false
server: false
lsi: false
markdown: kramdown
kramdown:
    parse_block_html: true;
pygments: true
permalink: /:year/:month/:title
paginate: 4
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]
