lsi: false
markdown: kramdown
kramdown:
    parse_block_html: true;
highlighter: rouge
permalink: /:year/:month/:title
paginate: 4
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]
description: "Technology blog about Web development and Open Source"
